Update nodejs versions
openshift-s2i/s2i-nodejs-community pull request #3
Opened 2017-02-15 03:12 UTC by luiscoms

2017-02-15 16:11 UTC, bparees requested changes
A bunch of the new imagestreams reference ryanj's dockerhub repo, but we don't have a way to push there, so those imagestreams aren't actually going to be able to import anything.  

Also for your "latest/current" imagestreams, I recommend being version agnostic so they don't have to be updated every time what they point to changes, see how we handle it here for example:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L18-L30

vs

https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L65-L78

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "name": "ryanj/centos7-s2i-nodejs:6.9.5"
should this be 7.5.0?

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "supports":"nodejs:6,nodejs:6.9,nodejs",
7?

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "tags": "builder,nodejs,nodejs-6.9.5",
7?

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +            "name": "current",
why do we need current *and* latest?

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "supports":"nodejs:6,nodejs:6.9,nodejs",
7

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "tags": "builder,nodejs,nodejs-6.9.5,nodejs-current",
7

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "tags": "builder,nodejs,nodejs-6.9.5,nodejs-latest",
7?

2017-02-15 16:11 UTC, bparees commented on centos7-s2i-nodejs.json
> +              "supports":"nodejs:7,nodejs:6.5,nodejs",
7.5?

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "supports":"nodejs:7,nodejs:6.5,nodejs",
7.5?

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "tags": "builder,nodejs,nodejs-6.9.5,nodejs-latest",
7?

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "name": "ryanj/centos7-s2i-nodejs:6.9.5"
7.5.0?

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "tags": "builder,nodejs,nodejs-6.9.5",
7

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "supports":"nodejs:6,nodejs:6.9,nodejs",
7

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "tags": "builder,nodejs,nodejs-6.9.5,nodejs-current",
7

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +              "supports":"nodejs:6,nodejs:6.9,nodejs",
7

2017-02-15 16:11 UTC, bparees commented on image-streams-candidate.json
> +            "name": "current",
why current+latest?

2017-02-15 16:11 UTC, bparees commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
6.9.5?

2017-02-15 18:45 UTC, luiscoms commented
@bparees Well, I updated these versions with the script provided on the project with `hack/rebuild.sh`, that update all versions on `Makefile`.

Then, I update the image streams adding the `7.5.0` to the latest and current tag and `6.9.5`.

This image exists on dockerhub?

2017-02-16 14:13 UTC, luiscoms commented
@bparees Any questions?

2017-02-16 18:57 UTC, bparees commented
@luiscoms it does answer the question about current vs latest in that you didn't introduce them (but i still don't think it makes sense to have both)

but based on way you added 7.5 it looks like the search/replace logic updated a bunch of stuff to 6.95 instead of 7.5, so it still needs to be cleaned up.  I imagine the script replaced all the 6.3 references w/ 6.95, so your new "7" imagestreams didn't then get updated properly since they no longer contained 6.3.

2017-02-16 19:08 UTC, luiscoms commented
@bparees I will replace them but my question is if I just replace the version or the namespace too.
These image exists on dockerhub?

2017-02-16 19:26 UTC, bparees commented
> @bparees I will replace them but my question is if I just replace the version or the namespace too.
These image exists on dockerhub?

they don't exist on dockerhub and we don't have any particular plans to build/push them to dockerhub.  if you're interested, you can push them to your dockerhub org and update the imagestreams to point there, or we can see if @ryanj is still interested in building the new versions and pushing them to his org.

2017-02-16 19:54 UTC, ryanj commented
@bparees I've been meaning to roll out a 7.x image. I'd be happy to fix the automation scripts to cover this. Do builds still need to be run using docker-1.09?

2017-02-16 20:01 UTC, bparees commented
> Do builds still need to be run using docker-1.09?

no, you can push w/ newer docker versions now and openshift should work fine.

2017-02-17 00:17 UTC, luiscoms commented
@bparees I just update the PR with your considerations and added support to build on Mac OS

2017-02-17 19:13 UTC, bparees commented on hack/build.sh
> +  $(python -m site --user-base)/bin/docker-squash -f $base ${IMAGE_NAME}:${version}
you're welcome to just delete the squashing logic entirely, we're moving away from it.

2017-02-17 19:13 UTC, bparees commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
is there a reason this has no value?

2017-02-17 19:59 UTC, luiscoms commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
The value is filled on build time

2017-02-17 20:03 UTC, luiscoms commented
@bparees I removed the squash logic

2017-02-17 20:46 UTC, bparees commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
why not remove it in the other Dockerfiles then?

2017-02-17 20:46 UTC, bparees commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
I'm just aiming for consistency here :)

2017-02-17 20:48 UTC, luiscoms commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
Well, I can remove there too

2017-02-17 20:53 UTC, bparees commented on nodejs.org/Dockerfile.onbuild
> +    NODE_VERSION= \
that works.

2017-02-18 16:06 UTC, luiscoms commented
@bparees Is it ok now?

2017-02-18 23:45 UTC, bparees commented
@luiscoms i'm validating your branch locally

2017-02-18 23:54 UTC, merged

2017-02-19 16:54 UTC, luiscoms commented
@ryanj @bparees  Thesse images will be published on Dockerhub or not?